version: "3"
    services:
        db:
            image: postgres
            environment:
                POSTGRES_PASSWORD: tycgis
                POSTGRES_USER: postgres
                POSTGRES_DB: cuardenodecampo
            ports:
                - 5432:5432
            volumes:
                - ./data:/var/lib/postgresql/data
            restart: always
        app:
          image: cuardenodecampoapi
          ports:
            - 5000:5000
